#:schema node_modules/wrangler/config-schema.json
name = "ai-personal-shopping-concierge"
compatibility_date = "2024-12-24"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
# Add any public environment variables here
